---
- name: Setup Webserver
  hosts: all 
  become: true
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Create a new directory for Ansible demo website files
      ansible.builtin.file:
        path: "{{ web_dir }}"
        state: directory

    - name: Copying the index html template
      ansible.builtin.template:
        src: index.html.j2
        dest: "{{ web_dir }}/index.html"

    - name: The httpd service is enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
      notify: Restart httpd

    - name: Open firewall port
      service: http
      state: enabled
      immediate: true
      permanent: true

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
        enabled: true 
