---
# tasks file for apache_webserver
- name: Install httpd
  ansible.builtin.yum:
    name: httpd
    state: latest

- name: Install requests python package
  pip:
    name: requests
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Create a new directory for Ansible demo website files
  ansible.builtin.file:
    path: "{{ web_dir }}"
    state: directory

- name: Copying the index html template
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ web_dir }}/index.html"

- name: The httpd service is enabled
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started
  notify: Restart httpd

- name: Open firewall port
  ansible.posix.firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true

